export const SET_DANH_SACH_LOAI_CONG_VIEC = "SET_DANH_SACH_LOAI_CONG_VIEC";

export const SET_LOAI_CONG_VIEC_ID = "SET_LOAI_CONG_VIEC_ID";

export const SET_DANH_SACH_CHI_TIET_LOAI_CONG_VIEC = "SET_DANH_SACH_CHI_TIET_LOAI_CONG_VIEC";
